create table users
(
    id            integer generated by default as identity
        primary key,
    name          varchar,
    email         varchar,
    password_hash varchar,
    created_at    timestamp,
    updated_at    timestamp
);

alter table users
    owner to postgres;

create table authors
(
    id        integer generated by default as identity
        primary key,
    name      varchar,
    biography text
);

alter table authors
    owner to postgres;

create table books
(
    id                integer generated by default as identity
        primary key,
    title             varchar,
    author_id         integer
        references authors,
    short_description text,
    published_date    date,
    created_at        timestamp,
    updated_at        timestamp
);

alter table books
    owner to postgres;

create table user_devices
(
    id            integer generated by default as identity
        primary key,
    user_id       integer
        references users,
    device_type   varchar,
    device_token  varchar,
    registered_at timestamp
);

alter table user_devices
    owner to postgres;

create table user_book_reading_histories
(
    id              integer generated by default as identity
        primary key,
    user_id         integer
        references users,
    book_id         integer
        references books,
    start_timestamp timestamp,
    end_timestamp   timestamp,
    last_page_read  integer,
    device_id       integer
        references user_devices,
    created_at      timestamp
);

alter table user_book_reading_histories
    owner to postgres;

create table notifications
(
    id         integer generated by default as identity
        primary key,
    user_id    integer
        references users,
    message    text,
    is_read    boolean,
    created_at timestamp
);

alter table notifications
    owner to postgres;

create table genres
(
    id   integer generated by default as identity
        primary key,
    name varchar
);

alter table genres
    owner to postgres;

create table book_genres
(
    id       integer generated by default as identity
        primary key,
    book_id  integer
        references books,
    genre_id integer
        references genres
);

alter table book_genres
    owner to postgres;

